### ISSUE TITLE
found bug with animation

### ISSUE THREAD

**Issue by keesoudwater34** [PredatorCZ/XenoMax#1] opened 2019-06-07 18:00 UTC
found with 2017 version on mythra's animation send l  she goes cripple. and some others dont loop that well. for example mythra send 01. happens on other caracters too the glitching spaz

**Comment by PredatorCZ** [comment] 2019-06-17 12:40
I'm afraid, that send_l is additive animation, those are unsupported.
As for send_01, I don't see any weird behavior.
If you happen to see any weird deformations on last frame, you can exclude this frame from animation range. There seems to be bug, where it adds one frame for no reason at all.

**Comment by keesoudwater34** [comment] 2019-06-21 09:52
should i extract it and send you the file so you can look at it? and allong
some other files that you might need?

**Comment by PredatorCZ** [comment] 2019-06-21 11:37
You don't need to send me anything, I have everything I need.
But you could send me a gif or video with an animation, where you think the problem is.

**Comment by keesoudwater34** [comment] 2019-08-23 15:45
i did some more testing i changed some settings and now it works again it might be a single time thing since i havent been able to reproduce it. sorry that it took so long to get back to you on it. i dont know if i can ask that here but ive spent a couple weeks trying to get the cutscene animations loaded in with your tool but i cant make sense of it. is there any way you can inplement them in your tool? sorry for the wasted time on the bug. and thank you for replying back.

**Comment by PredatorCZ** [comment] 2019-12-08 14:27
The issue has been fixed in version 1.2.
Please verify and close this issue, if everything is ok.

**Comment by keesoudwater34** [comment] 2019-12-08 21:38
ill close it cause it should be fine if fixed now. ive got some more i got
to pull out at the moment so that works out

**Closed as completed** 2019-12-16 22:54 UTC
Labels: bug, question
